version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=beaubaby
      - MONGO_PASSWORD=beau1234
      - SESSION_SECRET=myOldSecret
    command: npm run dev
