version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node_app:
    depends_on:
      - mongo
    build: .
    image: charlied0cker/node_app
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=beaubaby
      - MONGO_INITDB_ROOT_PASSWORD=beau1234
    volumes:
      - mongo-db:/data/da
  redis:
    image: redis

volumes:
  mongo-db:
